services:
  backend:
    build:
      context: .
      dockerfile: rust-dev.Dockerfile
    user: "$USER_ID:$GROUP_ID"
    depends_on: [ db ]
    volumes:
      - .:/app
    working_dir: /app/backend
    command: sh -c "cargo watch -x run" 
    environment:
      CARGO_HOME: .cargo
      DATABASE_URL: postgresql://nijsac@db/nijsac
      SQLX_OFFLINE: true
      VERSION: development
    ports: [ "127.0.0.1:3000:3000" ]

  db:
    image: postgres:17
    pull_policy: always
    environment:
      POSTGRES_USER: nijsac
      POSTGRES_DB: nijsac
      TZ: Europe/Amsterdam
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: [ "127.0.0.1:5432:5432" ]

  frontend:
    image: node:20
    depends_on: [ backend ]
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      REMOTE_API: http://backend:3000
    ports: [ "127.0.0.1:5173:5173" ]